### ISSUE TITLE
Episode not published

### ISSUE THREAD

**Issue by LauPaSat-pl** [weltonrodrigo/epicentrismo-em-debate#1]
Some time ago I started using repository using the same github action to upload my podcasts. Unfortunately sometimes there's a problem and the podcast isn't published. When I log into my Anchor account it is there with correct audio and date, but no title and no description. Did you encounter the same issue, and if yes do you hve some quick workaround?

**Comment by weltonrodrigo** [comment]
I'm sorry, not able to provide any support. But, if you want, let's take this conversation to the youtube-to-anchor repo.

From what you described, seems like an error after the upload is finished. probably the date. You can try disabling the date feature of youtube-to-anchorfm
